from __future__ import annotations

from typing import Protocol

from core.models import GraphEdge, GraphNode, IngestionJob, KnowledgeLink, SemanticDocument


class NexusRepository(Protocol):
    def add_job(self, job: IngestionJob) -> IngestionJob: ...

    def get_job(self, job_id: str) -> IngestionJob | None: ...

    def update_job(self, job: IngestionJob) -> IngestionJob: ...

    def list_jobs(self) -> list[IngestionJob]: ...

    def add_link(self, link: KnowledgeLink) -> KnowledgeLink: ...

    def list_links(self) -> list[KnowledgeLink]: ...

    def graph(self) -> tuple[list[GraphNode], list[GraphEdge]]: ...

    def add_document(self, document: SemanticDocument) -> SemanticDocument: ...

    def get_document(self, uri: str) -> SemanticDocument | None: ...

    def list_documents(self) -> list[SemanticDocument]: ...

    def delete_document(self, uri: str) -> None: ...
