from __future__ import annotations

from typing import Protocol

from knowledge_os.domain.models import (
    CandidateBatch,
    CandidateGraphItem,
    CandidateOntology,
    GraphEvidence,
)


class KnowledgeOSStore(Protocol):
    def add_batch(self, batch: CandidateBatch) -> CandidateBatch: ...
    def get_batch(self, batch_id: str) -> CandidateBatch | None: ...
    def update_batch(self, batch: CandidateBatch) -> CandidateBatch: ...
    def list_batches(self) -> list[CandidateBatch]: ...
    def add_candidate_ontology(self, ontology: CandidateOntology) -> CandidateOntology: ...
    def list_candidate_ontologies(self, batch_id: str) -> list[CandidateOntology]: ...
    def add_candidate_graph_item(self, item: CandidateGraphItem) -> CandidateGraphItem: ...
    def get_candidate_graph_item(self, item_id: str) -> CandidateGraphItem | None: ...
    def update_candidate_graph_item(self, item: CandidateGraphItem) -> CandidateGraphItem: ...
    def list_candidate_graph_items(self, batch_id: str) -> list[CandidateGraphItem]: ...
    def add_graph_evidence(self, evidence: GraphEvidence) -> GraphEvidence: ...
    def list_graph_evidence(self, source_uri: str | None = None, graph_item_id: str | None = None) -> list[GraphEvidence]: ...
    def update_graph_evidence(self, evidence: GraphEvidence) -> GraphEvidence: ...
    def mark_document_status(self, uri: str, status: str) -> None: ...
    def get_document_status(self, uri: str) -> str | None: ...
